apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    app: hello-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-deploy
  template:
    metadata:
      name: hello-deploy
      labels:
        app: hello-deploy
    spec:
      containers:
        - name: hello-deploy
          image: hello/k8s-demo
          ports:
            - containerPort: 3000
              name: nodejs-port
      