# permissions for end users to edit results.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: result-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebilder-test
    app.kubernetes.io/part-of: kubebilder-test
    app.kubernetes.io/managed-by: kustomize
  name: result-editor-role
rules:
- apiGroups:
  - batch.test.kubebuilder.io
  resources:
  - results
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.test.kubebuilder.io
  resources:
  - results/status
  verbs:
  - get
