# permissions for end users to view results.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: result-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebilder-test
    app.kubernetes.io/part-of: kubebilder-test
    app.kubernetes.io/managed-by: kustomize
  name: result-viewer-role
rules:
- apiGroups:
  - batch.test.kubebuilder.io
  resources:
  - results
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.test.kubebuilder.io
  resources:
  - results/status
  verbs:
  - get
