---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - allresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - allresources/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - allresources/status
  verbs:
  - get
  - patch
  - update
